<li class="styleguide__color color" id="styleguide-colors-{{color.type}}-{{color.name}}">
	<a href="#styleguide-colors-{{color.type}}-{{color.name}}">
		<div class="color__preview {{color.text_color}}" style="background:{{color.code}}"><div class="content">{{color.code}}</div></div>
		<div class="color__id"><span class="color__type">{{color.type}}</span><br><span class="color__name">{{color.name}}</span></div>
		<div class="color__description">{{color.description}}</div>
	</a>
</li>